#
# This file is part of the project tutteli/puma published under the Apache License 2.0
# For the full copyright and license information, please have a look at LICENSE in the
# root folder or visit https://github.com/robstoll/PuMa
#
login:
    path:   /login{ending}
    defaults: { _controller: "TutteliAppBundle:Security:login", ending: ""}
    methods: [GET]

login_check:
    path:   /login_check
    defaults: { _controller: "TutteliAppBundle:Security:loginCheck" }
    methods: [POST]    

login_csrf:
    path: /login/token
    defaults: { _controller: "TutteliAppBundle:Security:csrfToken" }    
    methods: [GET]
    
logout:
    path: /logout
    methods: [GET]    

home:
    path:   /
    defaults: { _controller: "FrameworkBundle:Redirect:redirect", route: "new_purchase"}
    methods: [GET]


purchases:
    path:   /purchases/
    defaults: { _controller: "FrameworkBundle:Redirect:redirect", route: "purchases_month"}
    methods: [GET]

purchases_currentMonth:
    path:   /purchases/month
    defaults: { _controller: "TutteliAppBundle:Purchase:currentMonth"}
    methods: [GET]

purchases_monthTpl:
    path:   /purchases/month.tpl
    defaults: { _controller: "TutteliAppBundle:Purchase:monthTpl"}
    methods: [GET]

purchases_monthAndYear_json:
    path:   /purchases/month-{month}-{year}.json
    defaults: { _controller: "TutteliAppBundle:Purchase:monthAndYearJson" }
    methods: [GET]

purchases_monthAndYear:
    path:   /purchases/month-{month}-{year}{ending}
    defaults: { _controller: "TutteliAppBundle:Purchase:monthAndYear", ending: ""}
    methods: [GET]

get_purchase_json: 
    path: /purchases/{purchaseId}.json
    defaults: { _controller: "TutteliAppBundle:Purchase:getJson"}
    methods: [GET]  
      
new_purchase:
    path:   /purchases/new{ending}
    defaults: { _controller: "TutteliAppBundle:Purchase:new", ending: ""}
    methods: [GET]
    
new_purchase_csrf:
    path:   /purchases/new/token
    defaults: { _controller: "TutteliAppBundle:Purchase:csrfToken" }
    methods: [GET]

post_purchase:
    path:   /purchases
    defaults: { _controller: "TutteliAppBundle:Purchase:post", ending: ""}
    methods: [POST]
    
edit_purchase:
    path: /purchases/{purchaseId}/edit{ending}
    defaults: { _controller: "TutteliAppBundle:Purchase:edit", ending: ""}
    methods: [GET]    
    
edit_purchase_tpl:
    path: /purchases/edit.tpl
    defaults: { _controller: "TutteliAppBundle:Purchase:editTpl" }
    methods: [GET]
        
put_purchase:
    path: /purchases/{purchaseId}
    defaults: { _controller: "TutteliAppBundle:Purchase:put" }
    methods: [PUT]    


accounting_csrf:
    path:   /accounting/token
    defaults: { _controller: "TutteliAppBundle:Accounting:csrfToken" }
    methods: [GET]    

accounting_terminateMonth:
    path:   /accounting/terminate-{month}-{year}
    defaults: { _controller: "TutteliAppBundle:Accounting:terminateMonth" }
    methods: [PUT]    

    
bills_currentYear:
    path:   /accounting/bills
    defaults: { _controller: "TutteliAppBundle:Bill:currentYear" }
    methods: [GET]

bills_yearTpl:
    path:   /accounting/bills.tpl
    defaults: { _controller: "TutteliAppBundle:Bill:yearTpl" }
    methods: [GET]

bills_year_json:
    path:   /accounting/bills-{year}.json
    defaults: { _controller: "TutteliAppBundle:Bill:yearJson" }
    methods: [GET]

bills_year:
    path:   /accounting/bills-{year}{ending}
    defaults: { _controller: "TutteliAppBundle:Bill:year", ending: ""}
    methods: [GET]


put_accounting_terminate:
    path:   /accounting/terminate-{month}-{year}
    defaults: { _controller: "TutteliAppBundle:Accounting:terminate" }
    methods: [PUT]
    

get_categories_json:
    path:   /categories.json
    defaults: { _controller: "TutteliAppBundle:Category:cgetJson" }
    methods: [GET]

get_category_json: 
    path: /categories/{categoryId}.json
    defaults: { _controller: "TutteliAppBundle:Category:getJson"}
    methods: [GET] 

get_categories:
    path:  /categories{ending}
    defaults: { _controller: "TutteliAppBundle:Category:cget", ending: ""}
    methods: [GET]

new_category:
    path: /categories/new{ending}
    defaults: { _controller: "TutteliAppBundle:Category:new", ending: ""}
    methods: [GET]  
    
new_category_csrf:
    path:   /categories/new/token
    defaults: { _controller: "TutteliAppBundle:Category:csrfToken" }
    methods: [GET]

post_category:
    path: /categories
    defaults: { _controller: "TutteliAppBundle:Category:post" }
    methods: [POST]    
    
edit_category:
    path: /categories/{categoryId}/edit{ending}
    defaults: { _controller: "TutteliAppBundle:Category:edit", ending: ""}
    methods: [GET]    
    
edit_categeory_tpl:
    path: /categories/edit.tpl
    defaults: { _controller: "TutteliAppBundle:Category:editTpl" }
    methods: [GET]    

put_category:
    path: /categories/{categoryId}
    defaults: { _controller: "TutteliAppBundle:Category:put" }
    methods: [PUT]
        

get_users_json:
    path:  /users.json
    defaults: { _controller: "TutteliAppBundle:User:cgetJson" }
    methods: [GET]

get_user_json: 
    path: /users/{userId}.json
    defaults: { _controller: "TutteliAppBundle:User:getJson" }
    methods: [GET]

get_users:
    path:  /users{ending}
    defaults: { _controller: "TutteliAppBundle:User:cget", ending: ""}
    methods: [GET]

new_user:
    path: /users/new{ending}
    defaults: { _controller: "TutteliAppBundle:User:new", ending: ""}
    methods: [GET]    

new_user_csrf:
    path:   /users/new/token
    defaults: { _controller: "TutteliAppBundle:User:csrfToken" }
    methods: [GET]

post_user:
    path: /users
    defaults: { _controller: "TutteliAppBundle:User:post" }
    methods: [POST]
    
edit_user:
    path: /users/{userId}/edit{ending}
    defaults: { _controller: "TutteliAppBundle:User:edit", ending: ""}
    methods: [GET]
    
edit_user_tpl:
    path: /users/edit.tpl
    defaults: { _controller: "TutteliAppBundle:User:editTpl" }
    methods: [GET]
    
put_user:
    path: /users/{userId}
    defaults: { _controller: "TutteliAppBundle:User:put" }
    methods: [PUT]    
    
edit_user_password:
    path: /users/{userId}/change-password{ending}
    defaults: { _controller: "TutteliAppBundle:User:changePassword", ending: ""}
    methods: [GET]

edit_user_password_tpl:
    path: /users/change-password.tpl
    defaults: { _controller: "TutteliAppBundle:User:changePasswordTpl" }
    methods: [GET]    

put_user_password:
    path: /users/{userId}/change-password
    defaults: { _controller: "TutteliAppBundle:User:putChangePassword" }
    methods: [PUT]
    
reset_user_password:
    path: /users/{userId}/reset-password{ending}
    defaults: { _controller: "TutteliAppBundle:User:resetPassword", ending: ""}
    methods: [GET]      
    
reset_user_password_tpl:
    path: /users/reset-password.tpl
    defaults: { _controller: "TutteliAppBundle:User:resetPasswordTpl" }
    methods: [GET]        
    
put_reset_user_password:
    path: /users/{userId}/reset-password
    defaults: { _controller: "TutteliAppBundle:User:putResetPassword" }
    methods: [PUT]
    