#
# This file is part of the project tutteli/purchase published under the Apache License 2.0
# For the full copyright and license information, please have a look at LICENSE in the
# root folder or visit https://github.com/robstoll/purchase
#
login:
    path:   /login{ending}
    defaults: { _controller: TutteliAppBundle:Security:login, ending: ""}
    methods: [GET]

login_check:
    path:   /login_check
    defaults: { _controller: TutteliAppBundle:Security:loginCheck }
    methods: [POST]    

login_csrf:
    path: /login/token
    defaults: { _controller: TutteliAppBundle:Security:csrfToken }    
    methods: [GET]
    
logout:
    path: /logout
    methods: [GET]

home:
    path:   /
    defaults: 
      _controller: FrameworkBundle:Redirect:redirect
      route:  new_purchase
    methods: [GET]


new_purchase:
    path:   /purchases/new{ending}
    defaults: { _controller: TutteliAppBundle:Purchase:new, ending: ""}
    methods: [GET]
    
new_purchase_token:
    path:   /purchases/new/token
    defaults: { _controller: TutteliAppBundle:Purchase:csrfToken, ending: ""}
    methods: [GET]

post_purchase:
    path:   /purchases{ending}
    defaults: { _controller: TutteliAppBundle:Purchase:post, ending: ""}
    methods: [POST]
    
    
get_categories:
    path:   /categories
    defaults: { _controller: TutteliAppBundle:Category:cget }
    
get_users:
    path:  /admin/users{ending}
    defaults: { _controller: TutteliAppBundle:User:index, ending: ""}
    methods: [GET]    
    