#
# This file is part of the project tutteli/purchase published under the Apache License 2.0
# For the full copyright and license information, please have a look at LICENSE in the
# root folder or visit https://github.com/robstoll/purchase
#

tutteli_purchase:
    resource: "@TutteliPurchaseBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /login{ending}
    defaults: { _controller: TutteliAppBundle:Security:login, ending: ""}


login_check:
    path:   /login_check
    defaults: { _controller: TutteliAppBundle:Security:loginCheck }    
    
logout:
    path: /logout

admin_users:
    type: rest
    prefix: admin
    resource: Tutteli\AppBundle\Controller\UserController