#
# This file is part of the project tutteli/purchase published under the Apache License 2.0
# For the full copyright and license information, please have a look at LICENSE in the
# root folder or visit https://github.com/robstoll/purchase
#
login:
    path:   /login{ending}
    defaults: { _controller: "TutteliAppBundle:Security:login", ending: ""}
    methods: [GET]

login_check:
    path:   /login_check
    defaults: { _controller: "TutteliAppBundle:Security:loginCheck" }
    methods: [POST]    

login_csrf:
    path: /login/token
    defaults: { _controller: "TutteliAppBundle:Security:csrfToken" }    
    methods: [GET]
    
logout:
    path: /logout
    methods: [GET]

home:
    path:   /
    defaults: 
      _controller: FrameworkBundle:Redirect:redirect
      route:  new_purchase
    methods: [GET]


new_purchase:
    path:   /purchases/new{ending}
    defaults: { _controller: "TutteliAppBundle:Purchase:new", ending: ""}
    methods: [GET]
    
new_purchase_csrf:
    path:   /purchases/new/token
    defaults: { _controller: "TutteliAppBundle:Purchase:csrfToken", ending: ""}
    methods: [GET]

post_purchase:
    path:   /purchases
    defaults: { _controller: "TutteliAppBundle:Purchase:post", ending: ""}
    methods: [POST]
    
    
get_categories_json:
    path:   /categories.json
    defaults: { _controller: "TutteliAppBundle:Category:cgetJson" }
    methods: [GET]


get_users_json:
    path:  /users.json
    defaults: { _controller: "TutteliAppBundle:User:cgetJson" }
    methods: [GET]

get_user: 
    path: /users/{userId}.json
    defaults: { _controller: "TutteliAppBundle:User:getJson", ending: ""}
    methods: [GET]

get_users:
    path:  /users{ending}
    defaults: { _controller: "TutteliAppBundle:User:cget", ending: ""}
    methods: [GET]

new_user:
    path: /users/new{ending}
    defaults: { _controller: "TutteliAppBundle:User:new", ending: ""}
    methods: [GET]    

new_user_csrf:
    path:   /users/new/token
    defaults: { _controller: "TutteliAppBundle:User:csrfToken", ending: ""}
    methods: [GET]

post_user:
    path: /users
    defaults: { _controller: "TutteliAppBundle:User:post" }
    methods: [POST]
    
edit_user:
    path: /users/{userId}/edit{ending}
    defaults: { _controller: "TutteliAppBundle:User:edit", ending: ""}
    methods: [GET]
    
edit_user_tpl:
    path: /users/edit.tpl
    defaults: { _controller: "TutteliAppBundle:User:editTpl" }
    methods: [GET]
    
put_user:
    path: /users/{userId}
    defaults: { _controller: "TutteliAppBundle:User:put" }
    methods: [PUT]
    
    
get_categories:
    path:  /categories{ending}
    defaults: { _controller: "TutteliAppBundle:Category:cget", ending: ""}
    methods: [GET]

new_category:
    path: /categories/new{ending}
    defaults: { _controller: "TutteliAppBundle:Category:new", ending: ""}
    methods: [GET]  
    
edit_category:
    path: /categories/{categoryId}/edit{ending}
    defaults: { _controller: "TutteliAppBundle:Category:edit", ending: ""}
    methods: [GET]    